services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: group6
      POSTGRES_USER: admin
      POSTGRES_DB: living_fit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - living-fit-network 

  pgadmin:
    image: dpage/pgadmin4
    container_name: living-fit-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org 
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8080:80" 
    volumes:
      - ./db:/var/lib/pgadmin/storage/
    networks:
      - living-fit-network 
    depends_on:
      - postgres

  express:
    image: living-fit-express 
    build:
      context: ./app/backend
    networks: 
    - living-fit-network   

volumes:
  postgres_data: {}

networks:
  living-fit-network: {}
