version: '3'
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: group6
      POSTGRES_USER: admin
      POSTGRES_DB: living_fit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data:
