services:
  postgres:
    image: postgres:17
    container_name: living-fit-postgres
    environment:
      POSTGRES_PASSWORD: group6
      POSTGRES_USER: admin
      POSTGRES_DB: living_fit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - living-fit-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: living-fit-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
    logging:
      driver: "none"
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    user: "${UID:-5050}:${GID:-5050}"
    networks:
      - living-fit-network
    depends_on:
      - postgres

  express:
    container_name: living-fit-express
    image: living-fit-express:latest
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      # bind mount to reflect changes
      - ./app/backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - living-fit-network

volumes:
  postgres_data: {}
  pgadmin_data: {}

networks:
  living-fit-network: {}
